stocks:
  - AAPL
  - GOOGL
  - MSFT
  - AMZN
  - TSLA
alpha_vantage:
  api_key: 'FLLR1T8T4ITKKGIP'

kafka:
  bootstrap_servers: 'kafka:9092'
  schema_registry_url: 'http://schema-registry:8081'
  topic_name: 'stock_prices'
